version: "3.8"

services:
  # PostgreSQL Database Service
  db: 
    image: postgres:14-alpine
    container_name: marketplace_db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-DBSECRETPASSWORD}
      POSTGRES_DB: ${DB_DATABASE:-resources_db}
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  # Backend Server Service
  server: 
    build: ./server
    container_name: marketplace_server # Corrected typo
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-DBSECRETPASSWORD}
      # This is the corrected line:
      - DB_HOST=db 
      - DB_PORT=${DB_PORT:-5432}
      - DB_DATABASE=${DB_DATABASE:-resources_db}
      - JWT_SECRET=${JWT_SECRET:-DBSECRETPASSWORD}
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
  
  # Frontend Client Service
  client:
    build: ./client
    container_name: marketplace_client # Corrected typo
    ports:
      - "3000:80"
    volumes:
      - ./client/src:/usr/src/app/src

volumes:
  postgres_data: